### PR TITLE
user :Help for python buffers

### PR DESCRIPTION
**Pull request by Konfekt**
:Help is rather meant for Vimscript and seems general enough a command to give it distinct meanings for distinct file types

### CODE REVIEW

**Comment by Konfekt** [comment]
By the way,

```vim
cabbr <expr> hh     <SID>canExpandHH() ? 'Help' : 'hh'
```

these [brittle abbreviations](https://stackoverflow.com/questions/3878692/how-to-create-an-alias-for-a-command-in-vim) to work around user-defined commands starting with an upper-case letter became common enough to think about  including [vim-alias](https://github.com/Konfekt/vim-alias/) upstream..

**Comment by girishji** [comment]
Sorry for the late reply. Thanks for these improvements!

**Comment by Konfekt** [comment]
Here's another one: since `:Help` as `&keywordprg`, for example on `import` sends one to vim(9)script docs, I'd rather keep it set to`pythondoc`.
But how about something like

```vim
exe 'nnoremap <buffer> dK :<c-u>Help <c-r><c-w>'..nr2char(&wildcharm)
```

?

**Comment by girishji** [comment]
Looks good! Feel free to make any necessary changes, and I'll go ahead with the merge.  As long as there's a command that exclusively invokes Python help files, I'm all set (if you think `:Help` is too generic).

**Pull request merged**
